In [20]:
import numpy as np
import cv2
import sys
import pandas as pd

In [21]:
cascPath = "haarcascade_frontalface_default.xml"

In [22]:
# Create the haar cascade
faceCascade = cv2.CascadeClassifier(cascPath)

In [23]:
# Load an color image in grayscale
image = cv2.imread(r'C:\Users\User\Desktop\New folder\image2.jpeg')


In [24]:
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
# Detect faces in the image
faces = faceCascade.detectMultiScale(
    image,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30, 30),
    flags = cv2.CASCADE_SCALE_IMAGE
    )

In [27]:
faces

array([[521, 120,  52,  52],
       [126, 533,  39,  39],
       [234, 120,  42,  42],
       [ 13,  31,  58,  58],
       [410,  31,  57,  57],
       [521,  36,  56,  56],
       [512, 530,  59,  59],
       [121, 132,  60,  60],
       [716, 112,  68,  68],
       [419, 516,  60,  60],
       [326, 518,  49,  49],
       [727, 519,  48,  48],
       [708,  10,  71,  71],
       [608, 110,  71,  71],
       [620, 399,  70,  70],
       [320, 235,  57,  57],
       [720, 232,  61,  61],
       [626, 328,  46,  46],
       [120, 300,  70,  70]], dtype=int32)

In [28]:
print("Found {0} faces!".format(len(faces)))

Found 19 faces!


In [29]:
# Draw a rectangle around the faces
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)

In [30]:
cv2.imshow("Faces found", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
col_1 = np.array(faces[:,0])
col_2 = np.array(faces[:,1])
    
        

In [32]:
col_1

array([521, 126, 234,  13, 410, 521, 512, 121, 716, 419, 326, 727, 708,
       608, 620, 320, 720, 626, 120], dtype=int32)

In [33]:
col_2

array([120, 533, 120,  31,  31,  36, 530, 132, 112, 516, 518, 519,  10,
       110, 399, 235, 232, 328, 300], dtype=int32)

In [34]:
#new_col = []
#for l in range(len(faces)):
    #new_col.append(col_1[l]+col_2[l])
    
#new_col
    

In [35]:
sub_list = []
for l in range(len(faces)):
    if (col_1[l]<=100) & (col_2[l]<=100):
        sub_list.append([0,0])
    elif (col_1[l]<=100) & (col_2[l]<=200):
        sub_list.append([0,1])
    elif (col_1[l]<=100) & (col_2[l]<=300):
        sub_list.append([0,2])
    elif (col_1[l]<=100) & (col_2[l]<=400):
        sub_list.append([0,3])
    elif (col_1[l]<=100) & (col_2[l]<=500):
        sub_list.append([0,4])
    elif (col_1[l]<=100) & (col_2[l]<=600):
        sub_list.append([0,5])
    elif (col_1[l]<=100) & (col_2[l]<=700):
        sub_list.append([0,6])
    elif (col_1[l]<=100) & (col_2[l]<=800):
        sub_list.append([0,7])
    elif (col_1[l]<=200) & (col_2[l]<=100):
        sub_list.append([1,0])
    elif (col_1[l]<=300) & (col_2[l]<=100):
        sub_list.append([2,0])
    elif (col_1[l]<=400) & (col_2[l]<=100):
        sub_list.append([3,0])
    elif (col_1[l]<=500) & (col_2[l]<=100):
        sub_list.append([4,0])
    elif (col_1[l]<=600) & (col_2[l]<=100):
        sub_list.append([5,0])
    elif (col_1[l]<=700) & (col_2[l]<=100):
        sub_list.append([6,0])
    elif (col_1[l]<=800) & (col_2[l]<=100):
        sub_list.append([7,0])
    elif (col_1[l]<=200) & (col_2[l]<=200):
        sub_list.append([1,1])
    elif (col_1[l]<=300) & (col_2[l]<=200):
        sub_list.append([2,1])
    elif (col_1[l]<=400) & (col_2[l]<=200):
        sub_list.append([3,1])
    elif (col_1[l]<=500) & (col_2[l]<=200):
        sub_list.append([4,1])
    elif (col_1[l]<=600) & (col_2[l]<=200):
        sub_list.append([5,1])
    elif (col_1[l]<=700) & (col_2[l]<=200):
        sub_list.append([6,1])
    elif (col_1[l]<=800) & (col_2[l]<=200):
        sub_list.append([7,1])
    elif (col_1[l]<=200) & (col_2[l]<=300):
        sub_list.append([1,2])
    elif (col_1[l]<=300) & (col_2[l]<=300):
        sub_list.append([2,2])
    elif (col_1[l]<=400) & (col_2[l]<=300):
        sub_list.append([3,2])
    elif (col_1[l]<=500) & (col_2[l]<=300):
        sub_list.append([4,2])
    elif (col_1[l]<=600) & (col_2[l]<=300):
        sub_list.append([5,2])
    elif (col_1[l]<=700) & (col_2[l]<=300):
        sub_list.append([6,2])
    elif (col_1[l]<=800) & (col_2[l]<=300):
        sub_list.append([7,2])
    elif (col_1[l]<=200) & (col_2[l]<=400):
        sub_list.append([1,3])
    elif (col_1[l]<=300) & (col_2[l]<=400):
        sub_list.append([2,3])
    elif (col_1[l]<=400) & (col_2[l]<=400):
        sub_list.append([3,3])
    elif (col_1[l]<=500) & (col_2[l]<=400):
        sub_list.append([4,3])
    elif (col_1[l]<=600) & (col_2[l]<=400):
        sub_list.append([5,3])
    elif (col_1[l]<=700) & (col_2[l]<=400):
        sub_list.append([6,3])
    elif (col_1[l]<=800) & (col_2[l]<=400):
        sub_list.append([7,3])
    elif (col_1[l]<=200) & (col_2[l]<=500):
        sub_list.append([1,4])
    elif (col_1[l]<=300) & (col_2[l]<=500):
        sub_list.append([2,4])
    elif (col_1[l]<=400) & (col_2[l]<=500):
        sub_list.append([3,4])
    elif (col_1[l]<=500) & (col_2[l]<=500):
        sub_list.append([4,4])
    elif (col_1[l]<=600) & (col_2[l]<=500):
        sub_list.append([5,4])
    elif (col_1[l]<=700) & (col_2[l]<=500):
        sub_list.append([6,4])
    elif (col_1[l]<=800) & (col_2[l]<=500):
        sub_list.append([7,4])
    elif (col_1[l]<=200) & (col_2[l]<=600):
        sub_list.append([1,5])
    elif (col_1[l]<=300) & (col_2[l]<=600):
        sub_list.append([2,5])
    elif (col_1[l]<=400) & (col_2[l]<=600):
        sub_list.append([3,5])
    elif (col_1[l]<=500) & (col_2[l]<=600):
        sub_list.append([4,5])
    elif (col_1[l]<=600) & (col_2[l]<=600):
        sub_list.append([5,5])
    elif (col_1[l]<=700) & (col_2[l]<=600):
        sub_list.append([6,5])
    elif (col_1[l]<=800) & (col_2[l]<=600):
        sub_list.append([7,5])
    elif (col_1[l]<=200) & (col_2[l]<=700):
        sub_list.append([1,6])
    elif (col_1[l]<=300) & (col_2[l]<=700):
        sub_list.append([2,6])
    elif (col_1[l]<=400) & (col_2[l]<=700):
        sub_list.append([3,6])
    elif (col_1[l]<=500) & (col_2[l]<=700):
        sub_list.append([4,6])
    elif (col_1[l]<=600) & (col_2[l]<=700):
        sub_list.append([5,6])
    elif (col_1[l]<=700) & (col_2[l]<=700):
        sub_list.append([6,6])
    elif (col_1[l]<=800) & (col_2[l]<=700):
        sub_list.append([7,6])
    elif (col_1[l]<=200) & (col_2[l]<=800):
        sub_list.append([1,7])
    elif (col_1[l]<=300) & (col_2[l]<=800):
        sub_list.append([2,7])
    elif (col_1[l]<=400) & (col_2[l]<=800):
        sub_list.append([3,7])
    elif (col_1[l]<=500) & (col_2[l]<=800):
        sub_list.append([4,7])
    elif (col_1[l]<=600) & (col_2[l]<=800):
        sub_list.append([5,7])
    elif (col_1[l]<=700) & (col_2[l]<=800):
        sub_list.append([6,7])
    elif (col_1[l]<=800) & (col_2[l]<=800):
        sub_list.append([7,7])

In [36]:
face_tiles = sub_list

In [37]:
face_tiles

[[5, 1],
 [1, 5],
 [2, 1],
 [0, 0],
 [4, 0],
 [5, 0],
 [5, 5],
 [1, 1],
 [7, 1],
 [4, 5],
 [3, 5],
 [7, 5],
 [7, 0],
 [6, 1],
 [6, 3],
 [3, 2],
 [7, 2],
 [6, 3],
 [1, 2]]